apiVersion: v1
kind: Service
metadata:
  name: aiops-api
  namespace: aiops
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: aiops-api
  ports:
    - name: http
      port: 8080
      targetPort: http
